spring:
  application:
    name: restaurant

  datasource:
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATABASE_USERNAME:postgres}
    password: ${SPRING_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

api:
  jwt-secret: ${JWT_SECRET:YourVeryLongSecretKeyThatIsAtLeast32Bytes}